name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: build
        run: |
          composer install --no-dev --optimize-autoloader --classmap-authoritative
          composer dump-autoload --no-dev --optimize --classmap-authoritative
          cp .github/.htaccess vendor/.htaccess
          rm -rf .git
          rm -rf .github
          rm -rf tests
          rm -rf .docker
          rm .php_cs.cache
          mkdir dpdbaltics
          rsync -Rr ./ ./dpdbaltics
          shopt -s extglob
          rm -r !(dpdbaltics)
          find . -maxdepth 1 -type f -exec rm "{}" \;
          cd dpdbaltics && rm -rf dpdbaltics
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dpdbaltics
          path: |